---
- name: JBoss deployment playbook
  hosts: all       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: root         # Update username for remote server
  roles:
    - jboss-standalone

